<div class="container">
    <div class="content">
        <div class="row">
            <div class="col-md-3">
                <div class="row pic">
                    <div class="col-md-12">
                        <input type="file" style="display: none;" name="photo" id="<?= $user->getId() ?>"/>
                        <img src='<?= $src ?>' alt="" class="img-thumbnail center_img">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12 nick_name">
                        <?= $user->getName() ?>
                    </div>
                </div>
            </div>

            <div class="col-md-9 cont">
                <div class="row add">
                    <div class="col-md-1 text-center first">
                        <button id="upload" type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
                            <i class="glyphicon glyphicon-paperclip"></i>
                        </button>
                    </div>
                    <form action='/note/create' method="post" class="form-signin async">
                        <div class="col-md-10">
                            <div class="form-group description">
                                <input type="hidden" name="file" value="">
                                <input class="form-control input-lg" id="ex1" name="desc" type="text" placeholder="Опис файлу">
                            </div>
                        </div>
                        <div class="col-md-1 text-center first">
                            <button type="submit" class="btn btn-default">
                                <i class="glyphicon glyphicon-send"></i>
                            </button>
                        </div>
                    </form>
                </div>

                <div class="wall">
                    <div class="added_file_block">
                        <div class="row added">
                            <div class="col-md-1 text-center first">
                                <i class="glyphicon glyphicon-floppy-saved"></i>
                            </div>

                            <div class="col-md-10">
                                <div class="description">

                                </div>
                            </div>

                            <div class="col-md-1 text-center first">
                                <form action='/file/download' method="post">
                                    <input type="hidden" name="fileName" value="DSC_0145.jpg">
                                    <button type="submit" class="btn btn-default">
                                        <i class="glyphicon glyphicon-save"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Загрузка файла</h4>
            </div>

            <div class="modal-body">
                <form action="/file/upload" class="dropzone" id="my-awesome-dropzone">
                    <div class="fallback">
                        <input name="file" type="file" />
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-default start">
                    <span>Загрузити</span>
                </button>
            </div>
        </div>
    </div>
</div>