<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <?= $this->tag->form(
            [
                'user/forgotPassword',
                'method' => "post",
                'id' => "loginform",
                'class' => "async"
            ]
        )
        ?>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" name="email" id="email" class="form-control">
            </div>
            <hr>
            <div class="text-right">
                <button class="btn btn-default">Send me recovery link to email</button>
            </div>
        </form>
    </div>
</div>