<?= $this->tag->stylesheetLink('css/signin.css'); ?>
<?= $this->tag->image([
            "img/1.png",
            'class' => 'hidden-xs hidden-md'
]);?>
<?= $this->tag->image([
            "img/2.png",
            'class' => 'hidden-lg hidden-md hidden-sm'
]);?>
<?= $this->tag->image([
            "img/3.png",
            'class' => 'hidden-lg hidden-sm hidden-xs'
]);?>
<div class="container formcoordination">
    <div class="col-md-8 ">
        <div class="text">
            <h1>Груповий<p>файлобмінник</p ><p class="f_name">FLOPPY.net</p></h1>
        </div>
    </div>
    <div class="col-md-4">
        <?= $this->tag->form(
            [
                '/user/login',
                'method' => "post",
                'class' => "form-signin async"
            ]
        )
        ?>
        <div class="form-group">
            <input name="email" type="text" id="inputEmail" class="form-control" placeholder="Електронна пошта">
        </div>
        <div class="form-group">
            <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Пароль">
            <span class="eye glyphicon glyphicon-eye-open"></span>
        </div>
        <button style="margin-top: 15px" class="btn btn-lg btn-primary btn-block" type="submit">
            <i class="glyphicon glyphicon-log-in"></i>Увійти
        </button>
        <a href="/user/register" class="btn btn-lg btn-primary btn-block">
            <i class="glyphicon glyphicon-user"></i>Зареєструватися
        </a>
        <?= $this->tag->endForm() ?>
    </div>
</div>