<div class="container">
    <div class="content">
        <div class="row">
            <?= $this->view->partial('profile/info') ?>
            <?php
            if (!$user['user']->hasSubscribed($this->session->get('user_identity')['id'], $user['user']->getId())) {
                $action = '/anotheruser/subscribe';
                $text = 'Subscribe';
            } else {
                $action = '/anotheruser/unsubscribe';
                $text = 'Unsubscribe';
            }
            ?>
            <form method="post" action="<?= $action ?>" class="buttom async">
                <input type="hidden" name="subscriber" value="<?= $user['user']->getId()?>">
                <button type="submit">
                    <span><?= $text ?></span>
                </button>
            </form>
            <div class="col-md-9 cont">
                <?= $this->view->partial('profile/wall') ?>
            </div>
        </div>
    </div>
</div>
