<div class="wall">
    <div class="added_file_block">
        <?php
        $articles = $user['user']->note;
        if ($articles->count() > 0) :
            $articles = array_reverse($articles->toArray());
            foreach ($articles as $note):
                ?>
                <div class="row added">
                    <div class="col-md-1 text-center first">
                        <i class="glyphicon glyphicon-floppy-saved"></i>
                    </div>
                    <div class="col-md-10">
                        <div class="descriptionText">
                            <?= $note['text'] ?>
                        </div>
                    </div>
                    <div class="col-md-1 text-center first">
                        <form action="/file/download" method="post">
                            <input type="hidden" name="fileName" value="<?= $note['file'] ?>">
                            <button title="Назва файла <?= $note['file'] ?>" type="submit" class="btn btn-default">
                                <i class="glyphicon glyphicon-save"></i>
                            </button>
                        </form>
                    </div>
                </div>
            <? endforeach; ?>
        <? else: ?>
            <h1>Стіна пуста</h1>
        <? endif; ?>
    </div>
</div>
